[source]
compiler_tests/strings/search.c: fail
Reason:
{no_ir,{function,{[{char,1}],
                  {{'*',1},
                   {{identifier,1,search},
                    [{declaration,[{char,1}],[{{'*',1},{identifier,1,x}}]},
                     {declaration,[{char,1}],[{identifier,1,c}]}]}},
                  [{{while,3},
                    {{'*',3},{identifier,3,x}},
                    [{{'if',4},
                      {bif,'==',[{{'*',4},{identifier,4,x}},{identifier,4,c}]},
                      [{{return,5},{identifier,5,x}}],
                      []},
                     {assign,{'=',7},
                             [{identifier,7,x},
                              {bif,'+',[{identifier,7,x},{int_l,7,1,[]}]}]}]},
                   {{return,9},{int_l,9,0,[]}}]}}}

*^ We can't declare functions which return a pointer for some reason.*

{no_mips,[{move,{i,1},{x,1}},
          {'+',[{x,0},{x,1}],{x,0}},
          {move,{i,119},{x,1}},
          {cast,{x,1},{0,u,8}},
          {store,{x,1},{x,0}}]}

*^ This should be in the IR? Is the array not flat?*

[source]
compiler_tests/functions/call_mutual_recursive.c: fail
Reason:
{{undefined_op_cast,'+'},
 {{[],{[],{0,i,32}}},{[],{[],{0,i,32}}}},
 {state,2,1,0,
        #{r1 => {{0,i,32},1},r2 => {{[],{0,i,32}},1}},
        #{{y,0} => 32},
        1,
        #{n => {{[],{0,i,32}},{y,0}}},
        #{},#{},#{},
        #{{x,0} => {[],{0,i,32}},
          {x,1} => {[],{0,i,32}},
          {y,0} => {[],{0,i,32}}}},
 {{identifier,8,r2},{apply,[{bif,'-',[{identifier,8,n},{int_l,8,1,[]}]}]}},
 {{identifier,8,r2},{apply,[{bif,'-',[{identifier,8,n},{int_l,8,1,[]}]}]}}}

 *^ This has double array specifiers on the types for some reason*

[source]
compiler_tests/array/index_variable.c: fail
Reason:
{not_const,{identifier,6,i}}

^ We can't calculate an offset to assign an array to.
